### ISSUE TITLE
Radar

### ISSUE THREAD

**Issue by DmitryArtyomov** [owerosu/linux-csgo-external#1]
Can the radar be fixed somehow? It was really helpful

**Comment by ericek111** [comment]
I will make a pull request to gogobebe2's repo today.

**Comment by owerosu** [comment]
I may try to fix netvar class in the next weeks.

**Comment by ericek111** [comment]
I've already mailed gogobebe2, but due to timezones, it's like 3 AM there... So here you go!
void Radar(remote::Handle* csgo, remote::MapModuleMemoryRegion* client, void* ent, hack::Entity* entity) {
    unsigned char spotted = 1;
    csgo->Write((void*) ((unsigned long) ent + 0xEC5), &spotted, sizeof(unsigned char));
}

Radar(csgo, client, g_glow[i].m_pEntity, &ent);

Structs here: http://www.unknowncheats.me/forum/1480346-post113.html

**Comment by owerosu** [comment]
Thanks for the offset.
However, fixing netvar class is still valuable to get a more update resistant hack.

**Comment by ericek111** [comment]
Agreed, however classes (and structs) are very unlikely to be changed. The offset is from Cre3per's dumper, possibly the same thing as printAllClasses(), but sorted and for 64-bit client.

**Comment by owerosu** [comment]
I need a way to dump the offset myself then just in case. And I'm planning to add other stuff, so more offsets that may change. Fixing netvar class would solve this issue.
